IMAGE_FORMATS = ('PNG', 'JPG', 'JPEG')

SMALLINT_DEBIT_CREDIT = ((0, 'Débito'), (1, 'Crédito'))

SMALLINT_BOOLEAN = ((0, 'Não'), (1, 'Sim'))

SMALLINT_ACTIVE = ((0, 'Inativo'), (1, 'Ativo'))

COIN_ASCII_SYMBOL = (
    ('BLR', 'Brasul Real'),
    ('USD', 'Dólar Americano')
)

COUNTRY_ASCII_SYMBOL = (
    ('de', 'Alemão'),
    ('ar', 'Árabe'),
    ('af', 'Africâner'),
    ('am', 'Amárico'),
    ('hy', 'Armênio'),
    ('az', 'Azerbaijano	CA CL'),
    ('eu', 'Basco'),
    ('bn', 'Bengali'),
    ('be', 'Bielorrusso'),
    ('my', 'Birmanês'),
    ('bs', 'Bósnio'),
    ('bg', 'Búlgaro'),
    ('pt-br', 'Brasil'),
    ('kn', 'Canarim'),
    ('cs', 'Checo'),
    ('si', 'Cingalês'),
    ('ko', 'Coreano'),
    ('gl', 'Galego'),
    ('ka', 'Georgiano'),
    ('gu', 'Guzerate'),
    ('el', 'Grego'),
    ('da', 'Dinamarquês'),
    ('es', 'Espanhol'),
    ('fo', 'Feroês'),
    ('fi', 'Finlandês'),
    ('fr', 'Francês'),
    ('cy', 'Galês'),
    ('he', 'Hebraico'),
    ('hi', 'Hindi'),
    ('nl', 'Holandês'),
    ('hu', 'Húngaro'),
    ('id', 'Indonésio'),
    ('en', 'Inglês'),
    ('en-cy', 'Inglês Chipre'),
    ('en-us', 'Inglês Estados Unidos'),
    ('en-gu', 'Inglês Guam'),
    ('en-hk', 'Inglês Hong Kong'),
    ('en-il', 'Inglês Israel'),
    ('en-it', 'Inglês Itália'),
    ('en-lr', 'Inglês Libéria'),
    ('en-lu', 'Inglês Luxemburgo'),
    ('en-my', 'Inglês Malásia'),
    ('en-nl', 'Inglês Países Baixos'),
    ('en-no', 'Inglês Noruega'),
    ('en-se', 'Inglês Suécia'),
    ('en-ch', 'Francês Suíça'),
    ('ga', 'Irlandês'),
    ('it', 'Italiano'),
    ('ja', 'Japonês'),
    ('km', 'Khmer'),
    ('mk', 'Macedônio'),
    ('mt', 'Maltês'),
    ('mr', 'Marati'),
    ('mn', 'Mongol'),
    ('ne', 'Nepalês'),
    ('no', 'Norueguês'),
    ('nn', 'Norueguês Nynorsk'),
    ('nb', 'Norueguês bokmål'),
    ('ro', 'Romeno'),
    ('ps', 'Pashto'),
    ('pl', 'Polonês'),
    ('pa', 'Punjabi'),
    ('ky', 'Quirguiz'),
    ('ru', 'Russo'),
    ('so', 'Somali'),
    ('sw', 'Suaíli'),
    ('sv', 'Sueco'),
    ('tg', 'Tadjique'),
    ('tl', 'Tagalog'),
    ('th', 'Tailandês'),
    ('ta', 'Tâmil'),
    ('te', 'Télugo'),
    ('tk', 'Turcomeno'),
    ('tr', 'Turco'),
    ('uz', 'Uzbeque'),
    ('vi', 'Vietnamita'),
    ('xh', 'Xhosa'),
    ('zh-cn', 'Chinês simplificado'),
    ('zh-tw', 'Chinês tradicional'),
    ('zh-sg', 'Chinês simplificado - Cingapura'),
    ('zh-hk', 'Chinês tradicional - Hong Kong, RAE da China'),
    ('zh-mo', 'Chinês tradicional - Macau, RAE da China'),
)