# Generated by Django 3.0.7 on 2020-07-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200705_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='dsc_cat',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='imagesdata',
            name='image',
            field=models.ImageField(default=None, upload_to='images/high'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagesdata',
            name='image_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='imagesdata',
            name='image_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='imagesdata',
            name='image_type',
            field=models.CharField(choices=[('jpg', 'Arquivo jpeg'), ('png', 'Arquivo png'), ('bmp', 'Arquivo bmp')], max_length=5),
        ),
        migrations.AlterField(
            model_name='imagesdata',
            name='image_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Comprimento'),
        ),
        migrations.AlterField(
            model_name='imagesdata',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnail'),
        ),
    ]
